<a href="https://colab.research.google.com/github/balureddy1379/Python-Lab-282/blob/main/3_0282.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array([1,3,0],float)
print(a)
print(a>2)

[1. 3. 0.]
[False  True False]


In [ ]:
import numpy as np
a=np.array([2,3,4])
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
b=np.array((2,3,4))
print(type(b))

<class 'numpy.ndarray'>


In [ ]:
import numpy as np
a=np.array([[1,3,5],[2,4,6]])
print(a[0][0])

1


In [ ]:
import numpy as np
a=np.array([[1,3,5],[2,4,6],[4,5,6]])
print(a[0][0])

1


In [ ]:
arr=np.zeros((3,3),int)
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
arr=np.empty((3,4))
print(arr)

[[4.68570668e-310 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]]


In [ ]:
arr=np.arange(10,50,20)
print(arr)

[10 30]


In [ ]:
arr=np.arange(0,2,0.3)
print(arr)

[0.  0.3 0.6 0.9 1.2 1.5 1.8]


In [ ]:
arr=np.linspace(0,2,9)
print(arr)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [ ]:
arr=np.identity(3,int)
print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
arr=np.random.randint(-10,1,9)
print(arr)

[-3 -4  0 -2 -2  0 -4 -6 -6]


In [6]:
def Quicksort(arr):
  if len(arr) <= 1:
    return arr
  pivot = arr[len(arr) // 2]
  left = [x for x in arr if x < pivot]
  middle = [x for x in arr if x == pivot]
  right = [x for x in arr if x > pivot]
  return Quicksort(left) + middle + Quicksort(right)

print(Quicksort([3,6,8,10,1,2,1]))

[1, 1, 2, 3, 6, 8, 10]
